### ISSUE TITLE
Move issues from old repo

### ISSUE THREAD

**Issue by giovannipizzi** [osscar-org/widget-periodictable#5]
@dou-du could you move the relevant issues from https://github.com/aiidalab/aiidalab-widget-periodictable/issues to here, or close those which are old?

So we can archive the other repo, otherwise people get confused on which one to use.

Same thing if there are other repos that have been moved.

**Comment by dou-du** [comment]
> @dou-du could you move the relevant issues from https://github.com/aiidalab/aiidalab-widget-periodictable/issues to here, or close those which are old?
> 
> So we can archive the other repo, otherwise people get confused on which one to use.
> 
> Same thing if there are other repos that have been moved.

Yes, I will do it.

**Comment by dou-du** [comment]
@giovannipizzi I do not have authorization to close the issues. Could you add me to that repository ?

**Comment by giovannipizzi** [comment]
Done

**Comment by dou-du** [comment]
@giovannipizzi I can close the issues. But I cannot transfer them to here.

**Comment by giovannipizzi** [comment]
Maybe now you can? Otherwise just copy paste the important text from those, in the worst case (they are not too many). Thanks!

**Comment by dou-du** [comment]
@giovannipizzi I still cannot transfer issues. I guess that Github do not allow to transfer between different organizations. So I just copied them here. Now you can archive the repository.

**Comment by giovannipizzi** [comment]
Thanks!
